name: Build and Deploy
on: [push]
jobs:
  build-and-deploy
    runs-on:ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: shirleypress-deploy
      uses: loshirleyve/shirleypress@master
      env:
        ACCESS_TOKEN: ${{ secrets.SHIRLEY_PRESS_AUTO_DEPLOY }}
        TARGET_REPO: loshirleyve/shirleypress
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn docs:build  
        BUILD_DIR: docs/.vuepress/dist